//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IMyService")]
    public interface IMyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/PopulateData", ReplyAction="http://tempuri.org/IMyService/PopulateDataResponse")]
        void PopulateData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/PopulateData", ReplyAction="http://tempuri.org/IMyService/PopulateDataResponse")]
        System.Threading.Tasks.Task PopulateDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetStockValue", ReplyAction="http://tempuri.org/IMyService/GetStockValueResponse")]
        double GetStockValue(string aSymbol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetStockValue", ReplyAction="http://tempuri.org/IMyService/GetStockValueResponse")]
        System.Threading.Tasks.Task<double> GetStockValueAsync(string aSymbol);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyServiceChannel : WebApplication.ServiceReference1.IMyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyServiceClient : System.ServiceModel.ClientBase<WebApplication.ServiceReference1.IMyService>, WebApplication.ServiceReference1.IMyService {
        
        public MyServiceClient() {
        }
        
        public MyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void PopulateData() {
            base.Channel.PopulateData();
        }
        
        public System.Threading.Tasks.Task PopulateDataAsync() {
            return base.Channel.PopulateDataAsync();
        }
        
        public double GetStockValue(string aSymbol) {
            return base.Channel.GetStockValue(aSymbol);
        }
        
        public System.Threading.Tasks.Task<double> GetStockValueAsync(string aSymbol) {
            return base.Channel.GetStockValueAsync(aSymbol);
        }
    }
}
