//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfMonoClient.localhost {
    
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="WcfMonoClient.localhost", ConfigurationName="IMyService")]
public interface IMyService {
    
    // CODEGEN: Generating message contract since the wrapper namespace (http://tempuri.org/) of message PopulateDataRequest does not match the default value (WcfMonoClient.localhost)
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/PopulateData", ReplyAction="http://tempuri.org/IMyService/PopulateDataResponse")]
    PopulateDataResponse PopulateData(PopulateDataRequest request);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMyService/PopulateData", ReplyAction="http://tempuri.org/IMyService/PopulateDataResponse")]
    System.IAsyncResult BeginPopulateData(PopulateDataRequest request, System.AsyncCallback callback, object asyncState);
    
    PopulateDataResponse EndPopulateData(System.IAsyncResult result);
    
    // CODEGEN: Generating message contract since the wrapper namespace (http://tempuri.org/) of message GetStockValueRequest does not match the default value (WcfMonoClient.localhost)
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyService/GetStockValue", ReplyAction="http://tempuri.org/IMyService/GetStockValueResponse")]
    GetStockValueResponse GetStockValue(GetStockValueRequest request);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IMyService/GetStockValue", ReplyAction="http://tempuri.org/IMyService/GetStockValueResponse")]
    System.IAsyncResult BeginGetStockValue(GetStockValueRequest request, System.AsyncCallback callback, object asyncState);
    
    GetStockValueResponse EndGetStockValue(System.IAsyncResult result);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="PopulateData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class PopulateDataRequest {
    
    public PopulateDataRequest() {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="PopulateDataResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class PopulateDataResponse {
    
    public PopulateDataResponse() {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetStockValue", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GetStockValueRequest {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public string aSymbol;
    
    public GetStockValueRequest() {
    }
    
    public GetStockValueRequest(string aSymbol) {
        this.aSymbol = aSymbol;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="GetStockValueResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class GetStockValueResponse {
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public double GetStockValueResult;
    
    public GetStockValueResponse() {
    }
    
    public GetStockValueResponse(double GetStockValueResult) {
        this.GetStockValueResult = GetStockValueResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IMyServiceChannel : IMyService, System.ServiceModel.IClientChannel {
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class MyServiceClient : System.ServiceModel.ClientBase<IMyService>, IMyService {
    
    public MyServiceClient() {
    }
    
    public MyServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName) {
    }
    
    public MyServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public MyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public MyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress) {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    PopulateDataResponse IMyService.PopulateData(PopulateDataRequest request) {
        return base.Channel.PopulateData(request);
    }
    
    public void PopulateData() {
        PopulateDataRequest inValue = new PopulateDataRequest();
        PopulateDataResponse retVal = ((IMyService)(this)).PopulateData(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IMyService.BeginPopulateData(PopulateDataRequest request, System.AsyncCallback callback, object asyncState) {
        return base.Channel.BeginPopulateData(request, callback, asyncState);
    }
    
    public System.IAsyncResult BeginPopulateData(System.AsyncCallback callback, object asyncState) {
        PopulateDataRequest inValue = new PopulateDataRequest();
        return ((IMyService)(this)).BeginPopulateData(inValue, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    PopulateDataResponse IMyService.EndPopulateData(System.IAsyncResult result) {
        return base.Channel.EndPopulateData(result);
    }
    
    public void EndPopulateData(System.IAsyncResult result) {
        PopulateDataResponse retVal = ((IMyService)(this)).EndPopulateData(result);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetStockValueResponse IMyService.GetStockValue(GetStockValueRequest request) {
        return base.Channel.GetStockValue(request);
    }
    
    public double GetStockValue(string aSymbol) {
        GetStockValueRequest inValue = new GetStockValueRequest();
        inValue.aSymbol = aSymbol;
        GetStockValueResponse retVal = ((IMyService)(this)).GetStockValue(inValue);
        return retVal.GetStockValueResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult IMyService.BeginGetStockValue(GetStockValueRequest request, System.AsyncCallback callback, object asyncState) {
        return base.Channel.BeginGetStockValue(request, callback, asyncState);
    }
    
    public System.IAsyncResult BeginGetStockValue(string aSymbol, System.AsyncCallback callback, object asyncState) {
        GetStockValueRequest inValue = new GetStockValueRequest();
        inValue.aSymbol = aSymbol;
        return ((IMyService)(this)).BeginGetStockValue(inValue, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetStockValueResponse IMyService.EndGetStockValue(System.IAsyncResult result) {
        return base.Channel.EndGetStockValue(result);
    }
    
    public double EndGetStockValue(System.IAsyncResult result) {
        GetStockValueResponse retVal = ((IMyService)(this)).EndGetStockValue(result);
        return retVal.GetStockValueResult;
    }
}
